messdeck2/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.home_page,name="home"),
    path('admin/', admin.site.urls),
    path('staffdeck/',include('staffdeck.urls')),
    path('staffdeck/',include('django.contrib.auth.urls')),
    path('studeck/',include('studeck.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

studeck/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('accounts/',include("allauth.urls")),
    path("stulogin",views.stulogin),
    path("logout",views.log_out),
    path("stuhome",views.stuhome,name='stuhome'),
    path("",views.stulogin,name='stulogin'),
    path("feedback",views.feedback, name = 'feedback'),
    path("rating",views.menu_rating,name = "rating"),
    path('inc-attendance/', views.inc_attendance, name='inc_attendance'),
    path('stu_info',views.student_data,name="stu_info"),
    path('monthlymenu',views.monthmenu,name="monthmenu"),
]

studeck/models.py
from django.db import models
from django.contrib.auth.models import User  


class student_info(models.Model):
    user_name = models.ForeignKey(User, on_delete = models.CASCADE)
    student_bhawan = models.CharField(max_length=20)
    student_id = models.CharField(max_length=20)
    email = models.CharField(max_length=100)
    def __str__(self):
        return self.user_name.username
    
class Feedbacks(models.Model):
    user_name = models.ForeignKey(student_info,on_delete = models.CASCADE)
    feed_back = models.CharField(max_length=1000)
    picture = models.ImageField(upload_to="feedback_pics/",blank=True) 

class total_daily(models.Model):
    date = models.DateField()
    breakfast = models.IntegerField(default=0)
    lunch = models.IntegerField(default=0)
    dinner = models.IntegerField(default=0)

class user_total(models.Model):
    user_name = models.OneToOneField(student_info,on_delete=models.CASCADE)
    breakfast = models.IntegerField(default=0)
    lunch = models.IntegerField(default=0)
    dinner = models.IntegerField(default=0)

class food_items(models.Model):
    food_item = models.CharField(max_length=100)
    rating = models.FloatField(default=0)
    def __str__(self):
        return self.food_item

class rating_model(models.Model):
    food_item = models.ForeignKey(food_items, on_delete = models.CASCADE)
    user_name = models.ForeignKey(student_info, on_delete=models.CASCADE)
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

class checkpresence(models.Model):
    user_name = models.OneToOneField(student_info,on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    breakfast = models.IntegerField(default=0)
    lunch = models.IntegerField(default=0)
    dinner = models.IntegerField(default=0)

templates/stupages/feedback.html
{%if user.is_authenticated %}

{%load socialaccount %}
{% get_social_accounts user as accounts %}
{% if accounts %} 


    <html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title>Feedback</title>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>

  <style>

    
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins',sans-serif;
}
body{
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 10px;
  background: linear-gradient(135deg, #71b7e6, #9b59b6);
}
.container{
  max-width: 700px;
  width: 100%;
  background-color: #fff;
  padding: 25px 30px;
  border-radius: 5px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.15);
}
.container .title{
  font-size: 25px;
  font-weight: 500;
  position: relative;
}
.container .title::before{
  content: "";
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 30px;
  border-radius: 5px;
  background: linear-gradient(135deg, #71b7e6, #9b59b6);
}
.content form .user-details{
  flex-wrap: wrap;
  justify-content: space-between;
  margin: 20px 0 12px 0;
}
form .user-details .input-box{
  margin-bottom: 15px;
  width: calc(100% / 2 - 20px);
}
form .input-box span.details{
  display: block;
  font-weight: 500;
  margin-bottom: 5px;
}
.user-details .input-box input{
  height: 45px;
  width: 100%;
  outline: none;
  font-size: 16px;
  border-radius: 5px;
  padding-left: 15px;
  border: 1px solid #ccc;
  border-bottom-width: 2px;
  transition: all 0.3s ease;
}
.user-details .input-box input:focus,
.user-details .input-box input:valid{
  border-color: #9b59b6;
}
 form .gender-details .gender-title{
  font-size: 20px;
  font-weight: 500;
 }
 form .category{
   display: flex;
   width: 80%;
   margin: 14px 0 ;
   justify-content: space-between;
 }
 form .category label{
   display: flex;
   align-items: center;
   cursor: pointer;
 }
 form .category label .dot{
  height: 18px;
  width: 18px;
  border-radius: 50%;
  margin-right: 10px;
  background: #d9d9d9;
  border: 5px solid transparent;
  transition: all 0.3s ease;
}
 #dot-1:checked ~ .category label .one,
 #dot-2:checked ~ .category label .two,
 #dot-3:checked ~ .category label .three{
   background: #9b59b6;
   border-color: #d9d9d9;
 }
 form input[type="radio"]{
   display: none;
 }
 form .button{
   height: 45px;
   margin: 35px 0
 }
 form .button input{
   height: 100%;
   width: 100%;
   border-radius: 5px;
   border: none;
   color: #fff;
   font-size: 18px;
   font-weight: 500;
   letter-spacing: 1px;
   cursor: pointer;
   transition: all 0.3s ease;
   background: linear-gradient(135deg, #71b7e6, #9b59b6);
 }
 form .button input:hover{
  /* transform: scale(0.99); */
  background: linear-gradient(-135deg, #71b7e6, #9b59b6);
  }
 @media(max-width: 584px){
 .container{
  max-width: 100%;
}
form .user-details .input-box{
    margin-bottom: 15px;
    width: 100%;
  }
  form .category{
    width: 100%;
  }
  .content form .user-details{
    max-height: 300px;
    overflow-y: scroll;
  }
  .user-details::-webkit-scrollbar{
    width: 5px;
  }
  }
  @media(max-width: 459px){
  .container .content .category{
    flex-direction: column;
  }

}

  </style> 
<body>
  <div class="container">
    <div class="title">Feedback form</div>
    <div class="content">


            <form method="post" enctype="multipart/form-data">
                <div class="user-details">
                {% csrf_token %}

                {% if form.feed_back.field.required%}
                <div class="input-box">
                    <span class="details">Feedback</span>
                    <textarea type="text" style="height:15%; width: 212%; font-size: 20px;" name="feed_back" maxlength="1000" required id="id_feed_back">
                    </textarea>
                </div>

                    <span class="details">Feedback</span>
                    Picture(optional) {{ form.picture }}

                {% else %}
                    {{ form.feed_back }}
                    <p class="optional-field">This field is optional.</p>
                {% endif %}
        <div class="button">
          <input type="submit" value="Submit">
        </div>
      </form>
    </div>
  </div>

</body>
</html>
{%else%}
<script>
    window.location.href = "{% url 'home' %}";
  </script>

{%endif%}
{%else%}
<script>
    window.location.href = "{% url 'home' %}";
  </script>
{%endif%}

templates/stupages/monthlymenu.html
<html style="background-color: black    ;">
<div class="container">
{% if menu_data %}
{% for date, data in menu_data.items %}
  <div class="date-block"  padding: 10px; margin-bottom: 10px;">
    <h3>Date: {{ date }}</h3>
        <table border="2px" style="background-color: rgb(44, 42, 42);
        color: white; border: 2px solid rgb(55, 185, 228);">
           <tr>
        <th>meal</th>
         <th>Food</th>
        </tr>
            {% for time, food_list in data.items %}
        <tr>
         <td>{{ time }}</td>
        <td>
          <ul>
         {% for food in food_list %}
            <li>{{ food }}</li>
        {% endfor %}
        </ul>
        </td>
        </tr>
        {% endfor %}
        </table>
  </div>
{% endfor %}
{%else%}
 <h1> No menu available </h1>
 {%endif%}
 </div>
<style>

    .container{
        margin-left: 10px;
        background-color:rgba(27, 27, 27, 0.893)
    }
    .date-block {
        display:grid;
        margin: 20px;
        vertical-align: top; 
        margin-right: 20px;
        font-size: 30px;
        color: white;
    }
    ul {
        font-size: 15;
        margin-top: 0;
    }
 </style>


</html>

templates/stupages/rating.html
{%if user.is_authenticated %}
<html style="background-color:rgb(20, 19, 19); color:white">
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
   
    .button-1 {
  background-color: rgba(67, 197, 230, 0.768);
  border-radius: 8px;
  border-style: none;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: "Haas Grot Text R Web", "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  font-weight: 500;
  height: 40px;
  line-height: 20px;
  list-style: none;
  margin: 0;
  outline: none;
  padding: 10px 16px;
  position: relative;
  text-align: center;
  text-decoration: none;
  transition: color 100ms;
  vertical-align: baseline;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
}

.button-1:hover,
.button-1:focus {
  background-color: rgba(57, 168, 196, 0.768);
}
  .rate > input { 
    display: none;
  }
  .rate{
    display: inline-block;
    border: 0;
  }
  .rate > label {
    float: right;
    text-shadow: 0 0 1px black;
  }
  .rate > label::before{
    display: inline-block;
    font-size: 1.5rem;
    font-family: FontAwesome;
    content: "\f005";
    margin: 0;
    padding: 0.3rem .2ren;
    cursor: pointer;
  }

  input:checked ~ label, label:hover ~ label{
    color: yellow
  }
  input:checked + label:hover, input:checked ~ label:hover, input:checked ~ label:hover ~ label,
  label:hover ~ input:checked ~ label {
    color: rgb(217, 217, 7)
  }
  .container {
        display: flex;
        align-items: flex-start;
        gap: 100px;
      }

  .ratingtable{
    background-color: rgb(44, 42, 42);
    color: white;
    margin: 30px;
    display: grid;
  }

  
</style>
</head>

<body>
  
<div class="container">

<div class="avg-rating"> 
<table class="ratingtable" border="2px", style="border: 1px solid rgb(55, 185, 228);">
  <tr>
    <th>Food item</th>
    <th>Average rating</th>
  </tr>
  {%for food,rating in avg_rating.items %}
  <tr>
    <td>{{food}}</td>
    <td>{{rating}}</td>
  </tr>
  {%endfor%}
</table>
</div>

{%load socialaccount %}
{% get_social_accounts user as accounts %}
{% if accounts %} 
<div class="ratingform">
<form action="" method="POST">
  {%csrf_token%}
  <h3>Choose food item</h3>
  <select style="height: 50px; background-color: rgb(44, 42, 42); color: white;" name="selected_item" id="fooditems">  
    {%for item in itemlist%}
      <option value="{{item}}" >{{item}}</option>
    {%endfor%}
  </select>
  <p id="selectedItem"></p>
  <br>
  <h4>Rating</h4>
  <div class="rate">
    <input type="radio" name="rating" id="rating5" value="5" required /><label for="rating5" title="5"></label>
    <input type="radio" name="rating" id="rating4" value="4" required /><label for="rating4" title="4"></label>
    <input type="radio" name="rating" id="rating3" value="3" required /><label for="rating3" title="3"></label>
    <input type="radio" name="rating" id="rating2" value="2" required /><label for="rating2" title="2"></label>
    <input type="radio" name="rating" id="rating1" value="1" required /><label for="rating1" title="1"></label>
  </div>
  <br><br>
  <button class="button-1" type="submit">submit</button>
  {% if messages %}
<ul style="color: rgb(0, 255, 8); font-size: 30px;" class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</form>
</div>
{%endif%}
</div>
<script>
  document.getElementById('fooditems').addEventListener('change', function() {
    var selectedItem = this.value;
    document.getElementById('selectedItem').innerText = 'Selected item: ' + selectedItem;
  });
</script>

</body>


</html>
{%else%}
<script>
    window.location.href = "{% url 'home' %}";
  </script>

{%endif%}

templates/stupages/student_info.html
{%if user.is_authenticated %}
{%load socialaccount %}
{% get_social_accounts user as accounts %}
{% if accounts %} 
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title>Student information</title>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>

  <style>

    
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins',sans-serif;
}
body{
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 10px;
  background: linear-gradient(135deg, #71b7e6, #9b59b6);
}
.container{
  max-width: 700px;
  width: 100%;
  background-color: #fff;
  padding: 25px 30px;
  border-radius: 5px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.15);
}
.container .title{
  font-size: 25px;
  font-weight: 500;
  position: relative;
}
.container .title::before{
  content: "";
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 30px;
  border-radius: 5px;
  background: linear-gradient(135deg, #71b7e6, #9b59b6);
}
.content form .user-details{
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  margin: 20px 0 12px 0;
}
form .user-details .input-box{
  margin-bottom: 15px;
  width: calc(100% / 2 - 20px);
}
form .input-box span.details{
  display: block;
  font-weight: 500;
  margin-bottom: 5px;
}
.user-details .input-box input{
  height: 45px;
  width: 100%;
  outline: none;
  font-size: 16px;
  border-radius: 5px;
  padding-left: 15px;
  border: 1px solid #ccc;
  border-bottom-width: 2px;
  transition: all 0.3s ease;
}
.user-details .input-box input:focus,
.user-details .input-box input:valid{
  border-color: #9b59b6;
}
 form .gender-details .gender-title{
  font-size: 20px;
  font-weight: 500;
 }
 form .category{
   display: flex;
   width: 80%;
   margin: 14px 0 ;
   justify-content: space-between;
 }
 form .category label{
   display: flex;
   align-items: center;
   cursor: pointer;
 }
 form .category label .dot{
  height: 18px;
  width: 18px;
  border-radius: 50%;
  margin-right: 10px;
  background: #d9d9d9;
  border: 5px solid transparent;
  transition: all 0.3s ease;
}
 #dot-1:checked ~ .category label .one,
 #dot-2:checked ~ .category label .two,
 #dot-3:checked ~ .category label .three{
   background: #9b59b6;
   border-color: #d9d9d9;
 }
 form input[type="radio"]{
   display: none;
 }
 form .button{
   height: 45px;
   margin: 35px 0
 }
 form .button input{
   height: 100%;
   width: 100%;
   border-radius: 5px;
   border: none;
   color: #fff;
   font-size: 18px;
   font-weight: 500;
   letter-spacing: 1px;
   cursor: pointer;
   transition: all 0.3s ease;
   background: linear-gradient(135deg, #71b7e6, #9b59b6);
 }
 form .button input:hover{
  /* transform: scale(0.99); */
  background: linear-gradient(-135deg, #71b7e6, #9b59b6);
  }
 @media(max-width: 584px){
 .container{
  max-width: 100%;
}
form .user-details .input-box{
    margin-bottom: 15px;
    width: 100%;
  }
  form .category{
    width: 100%;
  }
  .content form .user-details{
    max-height: 300px;
    overflow-y: scroll;
  }
  .user-details::-webkit-scrollbar{
    width: 5px;
  }
  }
  @media(max-width: 459px){
  .container .content .category{
    flex-direction: column;
  }

}

  </style> 
<body>
  <div class="container">
    <div class="title">Student information</div>
    <div class="content">
      <form action="#" method="POST">
        {%csrf_token%}
        <div class="user-details">
          <div class="input-box">
            <span class="details">Bhawan</span>
          <select name="bhawan" id="bhawan" style="height: 50px; width:300px;   box-shadow: 0 5px 10px rgba(0,0,0,0.15);">  
            {%for item in bhawans%}
              <option value="{{item}}" >{{item}}</option>
            {%endfor%}
        </select>
        </div>


          <div class="input-box">
            <span class="details">ID</span>
            <input id="stu_id" name="stu_id" type="text" placeholder="your bits id" required>
          </div>
        </div>
        
        <div class="button">
          <input type="submit" value="Submit">
        </div>
      </form>
    </div>
  </div>

</body>
</html>

{%else%}
<script>
    window.location.href = "{% url 'home' %}";
  </script>

{%endif%}
{%else%}
<script>
    window.location.href = "{% url 'home' %}";
  </script>
{%endif%}